### ISSUE TITLE
Simulation appears over main menu when the server stops before the VR client disconnects

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-imd-vr#19]
Here is what I did

1. Start a server running GluHUT + glucose
2. Connect to the server in NanoVer iMD-VR
3. Hide solvent
4. Close the server
5. Try to open the left-hand menu, it appears at the origin of the box ([issue logged here](https://github.com/IRL2/nanover-vr-25/issues/18))
6. Disconnect from the server from the PC-VR menu
7. Simulation + waters appears. In one case, the main menu also appears, and in another the main menu does not appear. 

Here are videos showing this:

https://github.com/user-attachments/assets/c78ea228-462d-41cb-b5d9-fadede2e3173

https://github.com/user-attachments/assets/ea217481-489d-4f2f-a09f-2a2c87177e73

**Comment by Ragzouken** [comment]
Testing this today, I can't replicate the issue. I think it has been fixed in the meantime, but I'll wait until you check yourself, @rhoslynroebuck

**Comment by rhoslynroebuck** [comment]
I just tried to replicate this issue with the [latest Windows build](https://github.com/IRL2/nanover-imd-vr/releases/tag/2025.6.27) and `nanover-server` v0.1.2806. The issue has changed slightly, but is still there. These are the steps:

1. Load solvent system onto a server.
2. Connect VR client using the Windows build
3. Hide the solvent
4. Close the server

From this point, I run into three problems:
1. Nothing happens when I click the left-hand menu button to return to the main menu
2. I click `Disconnect` on the monitor UI and the solvent flashes up for a short time, then disappears again 
3. Even once I've clicked `Disconnect` I am still in the 'simulation'. I cannot see any molecules, but I can open the handheld menus and the main menu is not visible

Here is a video:

https://github.com/user-attachments/assets/73a5468e-ebba-4961-ad6a-c1ad52af31b1

**Comment by Ragzouken** [comment]
I'm still having trouble replicating the menu issues, but I've been able to fix the solvent flashing when you disconnect. I'll try to get you to demonstrate this to me on a test build and see if it's still there.

**Comment by rhoslynroebuck** [comment]
I just tested this issue again with the latest release (2025.6.30), here are the updates:

- The solvent/simulation no longer flashes up once the client disconnects. 
- However, I still cannot interact with the handheld menu once the server is closed. 

1. Start server and connect the VR client. 
2. Close the server.
3. At this point, pressing the buttons on the left handheld menu does nothing. 
4. Disconnect the client using the desktop UI. 
5. Now I can interact with the left handheld menu again, e.g. to return to the main menu.

**Comment by Ragzouken** [comment]
I can finally replicate this, at least in the windows build, not sure what changed though. I'll see if I can track down what's happening.
